server:
  port: 8091

task:
  danmu:
    - desc: 庆余年第一季
      enable: false #是否启用
      immediately: false  #启动后是否立即执行一次
      timer: false #是否启用定时任务
      cron: 5 * * * * ? #定时任务
      delMark: 腾讯弹幕 #删除旧的ass文件包含的标志,为空则不删除
      reName: 腾讯弹幕($@{FormatDate(${time},yyyy-MM-dd)}) #用于保存处理完成后的文件名,${time}标识当前时间,FormatDate时间函数
      source: #腾讯视频的播放页面,如果多页就需要配多个URL
        - https://v.qq.com/x/cover/rjae621myqca41h/i0032qxbi2v.html
        - https://v.qq.com/x/cover/rjae621myqca41h/v0033usud3k.html
      path: C:\Users\zxp21\Videos\弹幕\庆余年 (2019)\Season 1 #保存到本地的路径
      type: vqq # 弹幕 类型 vqq 腾讯 iqiyi 爱奇艺
    - desc: 爱奇艺弹幕
      enable: true
      immediately: false
      timer: true
      cron: 0 30 3 * * ?
      delMark: 爱奇艺弹幕
      reName: 爱奇艺弹幕
      source:
        - https://www.iqiyi.com/v_2ffkws0bgr0.html
      path: C:\Users\zxp21\Videos\弹幕\隐秘的角落 (2020)\Season 1
      type: iqiyi

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/static/html/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/danmu.db
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: select 1
mybatis:
  mapper-locations: classpath:db/mapper/*.xml
  type-aliases-package: skiree.host.danmu.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: danmu
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true