server:
  port: 8099

task:
  danmu:
    - desc: 庆余年第一季
      enable: false #是否启用
      immediately: false  #启动后是否立即执行一次
      timer: false #是否启用定时任务
      cron: 5 * * * * ? #定时任务
      delMark: 腾讯弹幕 #删除旧的ass文件包含的标志,为空则不删除
      reName: 腾讯弹幕($@{FormatDate(${time},yyyy-MM-dd)}) #用于保存处理完成后的文件名,${time}标识当前时间,FormatDate时间函数
      source: #腾讯视频的播放页面,如果多页就需要配多个URL
        - https://v.qq.com/x/cover/rjae621myqca41h/i0032qxbi2v.html
        - https://v.qq.com/x/cover/rjae621myqca41h/v0033usud3k.html
      path: C:\Users\zxp21\Videos\弹幕\庆余年 (2019)\Season 1 #保存到本地的路径
      type: vqq # 弹幕 类型 vqq 腾讯 iqiyi 爱奇艺
    - desc: 庆余年第二季
      enable: false
      immediately: false
      timer: false
      cron: 0 30 3 * * ?
      delMark: 腾讯弹幕
      reName: 腾讯弹幕(24-06-05)
      source:
        - https://v.qq.com/x/cover/mzc002002kqssyu/q4100dpkd26.html
        - https://v.qq.com/x/cover/mzc002002kqssyu/v4100ydmxec.html
      path: C:\Users\zxp21\Videos\弹幕\庆余年 (2019)\Season 2
      type: vqq
    - desc: MacOS庆余年第二季
      enable: false
      immediately: true
      timer: false
      cron: 0 30 3 * * ?
      delMark: 腾讯弹幕
      reName: 腾讯弹幕($@{FormatDate(${time},yyyy-MM-dd)})
      source:
        - https://v.qq.com/x/cover/mzc002002kqssyu/q4100dpkd26.html
        - https://v.qq.com/x/cover/mzc002002kqssyu/v4100ydmxec.html
      path: /Users/anorak/Downloads/TestFileDir/庆余年 (2019)/Season 2
      type: vqq
    - desc: 爱奇艺弹幕
      enable: true
      immediately: true
      timer: false
      cron: 0 30 3 * * ?
      delMark: 爱奇艺弹幕
      reName: 爱奇艺弹幕
      path: C:\Users\zxp21\Videos\弹幕\隐秘的角落 (2020)\Season 1
      type: iqiyi
      tvId: 9000000005439200