package skiree.host.danmu.model.ass;

import lombok.Data;

import java.awt.font.FontRenderContext;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.List;

import java.awt.Font;

@Data
public class ASS {

    public static final List<String> PUBLIC_ASS1 = new ArrayList<>();
    public static final List<String> PUBLIC_ASS2 = new ArrayList<>();

    static {
        PUBLIC_ASS1.add("[Script Info]\n" +
                "; Script generated by Anorak\n" +
                "Title: TxDanMu ASS file\n" +
                "ScriptType: v4.00+\n" +
                "WrapStyle: 2");

        PUBLIC_ASS2.add("ScaledBorderAndShadow: yes\n");

        PUBLIC_ASS2.add("[Aegisub Project Garbage]\n" +
                "Last Style Storage: Default\n" +
                "Video Zoom Percent: 1.000000\n" +
                "Active Line: 2\n");

        PUBLIC_ASS2.add("[V4+ Styles]\n" +
                "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n" +
                "Style: Default-Box,Arial," + AssConf.size + ",&H00FFFFFF,&H00FFFFFF,&HC4000000,&HFF4E4E5E,0,0,0,0,100,100,0,0,1," + AssConf.border + ",0,2,135,135,55,1\n");

        PUBLIC_ASS2.add("[Events]\n" +
                "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text");
    }

    public static double calculateWidth(String text) {
        Font font = new Font("Arial", Font.BOLD, AssConf.size);
        FontRenderContext frc = new FontRenderContext(null, true, true);
        Rectangle2D bounds = font.getStringBounds(text, frc);
        return Math.ceil(bounds.getWidth());
    }

}