package skiree.host.danmu.data;

import lombok.Data;

import java.util.ArrayList;
import java.util.List;

@Data
public class ASS {

    public static final List<String> PUBLIC_ASS = new ArrayList<>();

    static {
        PUBLIC_ASS.add("[Script Info]\n" +
                "; Script generated by Anorak\n" +
                "Title: TxDanMu ASS file\n" +
                "ScriptType: v4.00+\n" +
                "WrapStyle: 2\n" +
                "PlayResX: 1920\n" +
                "PlayResY: 1080\n" +
                "ScaledBorderAndShadow: yes\n");
        PUBLIC_ASS.add("[Aegisub Project Garbage]\n" +
                "Last Style Storage: Default\n" +
                "Video Zoom Percent: 1.000000\n" +
                "Active Line: 2\n");
        PUBLIC_ASS.add("[V4+ Styles]\n" +
                "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n" +
                "Style: Default-Box,Arial,58,&H00FFFFFF,&H00FFFFFF,&HC4000000,&HFF4E4E5E,0,0,0,0,100,100,0,0,1,23,0,2,135,135,65,1\n");
        PUBLIC_ASS.add("[Events]\n" +
                "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text");
    }

}
